import {createSlice, PayloadAction} from '@reduxjs/toolkit';
import itemType from '../typesData';

// Define the interface for the state of the slice
export interface ItemProps {
  filteredItems: itemType[];
}

// Define the initial state for the slice
const initialState: ItemProps = {
  filteredItems: [],
};

// Create a Redux Toolkit slice with the name 'filteredItems'
const FilteredItemSlice = createSlice({
  name: 'filteredItems',
  initialState,
  reducers: {
    // set stte for filteredItems
    setFilteredItems: (state, action: PayloadAction<itemType[]>) => {
      state.filteredItems = action.payload;
    },
  },
});

// Extract the 'setFilteredItems' action creator from the slice
export const {setFilteredItems} = FilteredItemSlice.actions;

// Export the reducer function generated by the slice
export default FilteredItemSlice.reducer;
