import {createSlice} from '@reduxjs/toolkit';

export interface CountProps {
  ItemCount: number;
}

const initialState: CountProps = {
  ItemCount: 0,
};

// Create a Redux Toolkit slice with the name 'ItemCount'
const ItemCountSlice = createSlice({
  name: 'ItemCount',
  initialState,
  reducers: {
    // Reducer function to increment the item count by 1
    setItemCount: state => {
      state.ItemCount = state.ItemCount + 1;
    },

    // Reducer function to decrement the item count by 1
    setItemCountDeduction: state => {
      state.ItemCount = state.ItemCount - 1;
    },

    // Reducer function to reset the item count to 0
    resetItemCount: state => {
      state.ItemCount = 0;
    },
  },
});

// Extract the action creators from the slice
export const {setItemCount, resetItemCount, setItemCountDeduction} =
  ItemCountSlice.actions;

// Export the reducer function generated by the slice
export default ItemCountSlice.reducer;
