// Import necessary dependencies from Redux Toolkit
import {createSlice, PayloadAction} from '@reduxjs/toolkit';

// Define the interface for the state of the slice
export interface QuantityProps {
  quantities: number[];
}

// Define the initial state for the slice
const initialState: QuantityProps = {
  quantities: [],
};

// Create a Redux Toolkit slice with the name 'quantity'
const QuantityItemSlice = createSlice({
  name: 'quantity',
  initialState,
  reducers: {
    // Reducer function to set quantities
    setQuantity: (state, action: PayloadAction<number[]>) => {
      state.quantities = action.payload;
    },

    // Reducer function to increment quantity at a specific index
    incrementQuantity: (state, action: PayloadAction<number>) => {
      const index = action.payload;
      state.quantities[index] += 1;
    },

    // Reducer function to decrement quantity at a specific index, with a minimum of 1
    decrementQuantity: (state, action: PayloadAction<number>) => {
      const index = action.payload;
      state.quantities[index] = Math.max(1, state.quantities[index] - 1);
    },
  },
});

// Extract the action creators from the slice
export const {setQuantity, incrementQuantity, decrementQuantity} =
  QuantityItemSlice.actions;

// Export the reducer function generated by the slice
export default QuantityItemSlice.reducer;
