import {createSlice, PayloadAction} from '@reduxjs/toolkit';
// Define the interface for the state of the slice
export interface TitleProps {
  searchTitle: string;
}

// Define the initial state for the slice
const initialState: TitleProps = {
  searchTitle: '',
};

// Create a Redux Toolkit slice with the name 'searchTitle'
const SearchTitleSlice = createSlice({
  name: 'searchTitle',
  initialState,
  reducers: {
    // Reducer function to set the search title
    setSearchTitle: (state, action: PayloadAction<string>) => {
      state.searchTitle = action.payload;
    },
  },
});

// Extract the action creator from the slice
export const {setSearchTitle} = SearchTitleSlice.actions;

// Export the reducer function generated by the slice
export default SearchTitleSlice.reducer;
